language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - tree

install:
  - cargo install mdbook

script:
  - PATH=$PATH:/home/travis/.cargo/bin mdbook test
  - PATH=$PATH:/home/travis/.cargo/bin mdbook build
  
after_success:
  - tree .
  - zip too-many-lists.zip rust.css
  - zip -r too-many-lists.zip book

deploy:
  provider: releases
  api_key: "$GH_DEPLOY_TOKEN"
  file: "too-many-lists.zip"
  skip_cleanup: true
  on:
    tags: true
