language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - tree

install:
  - git clone --depth 1 https://github.com/steveklabnik/rustbook.git
  - cd rustbook && cargo build --release && cd ..

script:
  - rustbook/target/release/rustbook build text/ book/

after_success:
  - tree book
  - zip -r too-many-lists book
